(package "show-eol"
         "0.0.5"
         "Show end of line symbol in buffer")

(website-url "https://github.com/jcs-elpa/show-eol")
(keywords "convenience" "end" "eol" "line")

(package-file "show-eol.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "24.4")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
